import * as cn from "src/application/services/connection.service";
import { GetInfoGeneralDto } from "../dtos/get-info-general.dto";
import { ResumenI } from "../interfaces/resumen.interface";

export const getResumen = async (dto: GetInfoGeneralDto, context: string): Promise<ResumenI> => {
  let addCond: string;
  if (+dto.centro1 === 1 && +dto.centro2 === 2) {
    addCond = "";
  } else {
    addCond = "AND ADNCENATE IN(@2, @3)";
  }
  try {
    const result = await cn.getDataSource(context).query(
      `SELECT
      COUNT(SFATOTFAC)FACTURAS,
      SUM(SFATOTFAC) TOTALFACTURADO,
      COUNT(CASE WHEN SFADOCANU = 1 AND CRNRADFACC IS NULL AND SFATIPDOC IN(1, 16) THEN SFADOCANU ELSE NULL END) AS ANULADAS,
      COUNT(CASE WHEN SFATIPDOC IN(0) THEN SLNFACTUR ELSE NULL END)PARTICULAR,
      SUM(CASE WHEN SFADOCANU = 1 AND CRNRADFACC IS NULL THEN SFATOTFAC ELSE NULL END) AS TOTALANULADO,
      COUNT(CASE WHEN SFATIPDOC IN(1, 16) THEN SLNFACTUR ELSE NULL END)
      -COUNT(CASE WHEN SFADOCANU = 1 AND CRNRADFACC IS NULL AND SFATIPDOC IN(1, 16) THEN SFADOCANU ELSE NULL END) RADICABLES,
      SUM(CASE WHEN SFATIPDOC IN(1, 16) THEN SFATOTFAC ELSE NULL END)
      -SUM(CASE WHEN SFADOCANU = 1 AND CRNRADFACC IS NULL AND SFATIPDOC IN(1, 16)THEN SFATOTFAC ELSE NULL END) TOTALRADICABLE,
      COUNT(CASE WHEN SFATIPDOC IN(1, 16) THEN CRDVALRAD ELSE NULL END) RADICADOS,
      SUM(CASE WHEN SFATIPDOC IN(1, 16) THEN CRDVALRAD ELSE NULL END) TOTALRADICADO,
      (SUM(CRDVALRAD)/(SUM(CASE WHEN SFATIPDOC IN(1, 16) THEN SFATOTFAC ELSE NULL END)
      -SUM(CASE WHEN SFADOCANU = 1 AND CRNRADFACC IS NULL AND SFATIPDOC IN(1, 16) THEN SFATOTFAC ELSE NULL END)))*100 CUMPLIMIENTO,
      COUNT(CASE WHEN SLNFACTUR IS NOT NULL AND SFATIPDOC IN(1, 16) THEN SLNFACTUR ELSE NULL END) 
      - COUNT(CASE WHEN CRNRADFACC IS NOT NULL THEN CRNRADFACC ELSE NULL END)
      - COUNT(CASE WHEN CRNRADFACC IS NULL AND SFADOCANU = 1 AND SFATIPDOC IN(1, 16) THEN SFADOCANU ELSE NULL END) PENDIENTES,
      SUM(CASE WHEN SFATIPDOC IN(1, 16) THEN SFATOTFAC ELSE NULL END)
      -SUM(CASE WHEN SFADOCANU = 1 AND CRNRADFACC IS NULL AND SFATIPDOC IN(1, 16) THEN SFATOTFAC ELSE NULL END)
      -SUM(CASE WHEN SFATIPDOC IN(1, 16) THEN CRDVALRAD ELSE NULL END) TOTALPENDIENTES
      FROM GCVRADFACTUR WHERE CONVERT(DATE, SFAFECFAC, 103) BETWEEN @0 AND @1 ${addCond}
      AND ISNULL(CRFESTADO, 4) IN(-1, 0, 1, 2, 4)`,
      [dto.inicioReporte, dto.finalReporte, dto.centro1, dto.centro2]
    );
    return result[0];
  } catch (error) {
    cn.ThrBadReqExc();
  }
};
