import * as cn from "src/application/services/connection.service";
import { ContextsE } from "src/application/enums/contexts.enum";
import { GetAgrupadoresDto } from "../dtos/get-agrupadores.dto";
import { AgrupadorI } from "../interfaces/agrupador.interface";

export const getAgrupadoresFinales = async (
  dto: GetAgrupadoresDto,
  context: string
): Promise<AgrupadorI[]> => {
  let query: string;
  let parameters: any[] = [];
  if (context === ContextsE.VALLEDUPAR) {
    query = `SELECT 
    F.AGRUPADOR Agrupador,
    ISNULL(SUM(CONS.SFAVALCAR),0) TotalEjecutado,
    F.TOTALFACTURADO TotalFacturado,
    COUNT(CONS.AINCONSEC) Iteraciones, 
    F.NEVENTOS Eventos,
    (F.NEVENTOS-COUNT(CONS.AINCONSEC)) EventosSobrantes,
    ISNULL((SUM(CONS.SFAVALCAR) /COUNT(CONS.AINCONSEC)),0) CmeEjecutado,
    (F.TOTALFACTURADO / NULLIF(F.NEVENTOS, 0)) CmeFacturado,
    ISNULL(F.TOTALFACTURADO -SUM(CONS.SFAVALCAR), 0) ErrorAbsoluto,
    ISNULL(ROUND(((F.TOTALFACTURADO - SUM(CONS.SFAVALCAR))/NULLIF(F.TOTALFACTURADO, 0))*100, 2),0) ErrorRelativo,
    ISNULL(ROUND((SUM(CONS.SFAVALCAR)/NULLIF(F.TOTALFACTURADO, 0))*100 ,2), 0) Porcentaje
     FROM ADNINGRESO RIGHT JOIN 
    (
    SELECT  
    TOP 1 WITH TIES
    ISNULL(G.ORDEN, 0) ORDEN,
       ISNULL(G.AGRUPADOR, 'EVENTOS')AS AGRUPADOR,
       ADNINGRESO.AINCONSEC,
      SLNFACTUR.SFAVALCAR,
      SLNFACTUR.SFAVALREC
        FROM SLNFACTUR
         INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
         INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
         INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
         LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
         LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
         LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
         LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
         LEFT JOIN GCMAGRUPGP G ON RTrim(LTrim(GENSERIPS.SIPCODCUP)) = G.COD_CUPS	
         AND G.CONTRATO = @2  
        WHERE 
        SLNFACTUR.SFATIPDOC = 17
        AND SLNFACTUR.SFADOCANU = N'0' 
        AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @0 AND @1
        AND GENDETCON.GDECODIGO = @2
        AND SLNORDSER.SOSESTADO = 1
        GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC, SLNFACTUR.SFAVALCAR, SLNFACTUR.SFAVALREC
        ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC)
        )  CONS ON CONS.AINCONSEC = ADNINGRESO.AINCONSEC 
        RIGHT JOIN GCMFICHCON F ON F.AGRUPADOR = CONS.AGRUPADOR
        WHERE F.GDECODIGO =  @2
        GROUP BY F.AGRUPADOR, F.ORDEN, F.TOTALFACTURADO, F.NEVENTOS ORDER BY F.ORDEN DESC;`;
    parameters = [dto.inicioReporte, dto.finalReporte, dto.contrato1];
  } else if (context === ContextsE.ALTACENTRO) {
    const common = `SELECT 
    F.AGRUPADOR Agrupador,
    ISNULL(SUM(CONS.SFAVALCAR),0) TotalEjecutado,
    ISNULL(NULLIF(F.TOTALFACTURADO, 0), 0) TotalFacturado,
    COUNT(CONS.AINCONSEC) Iteraciones, 
    F.NEVENTOS Eventos,
    (F.NEVENTOS-COUNT(CONS.AINCONSEC)) EventosSobrantes,
    ISNULL((SUM(CONS.SFAVALCAR) /COUNT(CONS.AINCONSEC)),0) CmeEjecutado,
    ISNULL((F.TOTALFACTURADO / NULLIF(F.NEVENTOS, 0)), 0) CmeFacturado,
    ISNULL(F.TOTALFACTURADO -SUM(CONS.SFAVALCAR), 0) ErrorAbsoluto,
    ISNULL(ROUND(((F.TOTALFACTURADO - SUM(CONS.SFAVALCAR))/ NULLIF(F.TOTALFACTURADO, 0))*100, 2),0) ErrorRelativo,
    ISNULL(ROUND((SUM(CONS.SFAVALCAR)/ NULLIF(F.TOTALFACTURADO, 0))*100 ,2), 0) Porcentaje
     FROM ADNINGRESO RIGHT JOIN 
    (
SELECT  
    TOP 1 WITH TIES
    ISNULL(G.ORDEN, 0) ORDEN,
       ISNULL(G.AGRUPADOR, 'EVENTOS')AS AGRUPADOR,
       ADNINGRESO.AINCONSEC,
        SLNFACTUR.SFAVALCAR,
        SLNFACTUR.SFAVALREC
            FROM SLNFACTUR
             INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
             INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
             INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
             LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
             LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
             LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
             LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
             LEFT JOIN GCMAGRUPGP G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS`;
    if (dto.contrato1 === "8005") {
      query = `${common} AND G.CONTRATO = @3   
      WHERE 
      SLNFACTUR.SFATIPDOC = 17
      AND SLNFACTUR.SFADOCANU = N'0' 
      AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @0 AND @1
      AND GENDETCON.GDECODIGO IN(@2, @3)
      AND SLNORDSER.SOSESTADO = 1
      GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC, SLNFACTUR.SFAVALCAR, SLNFACTUR.SFAVALREC
      ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC)
)  CONS ON CONS.AINCONSEC = ADNINGRESO.AINCONSEC 
      RIGHT JOIN GCMFICHCON F ON F.AGRUPADOR = CONS.AGRUPADOR
      LEFT JOIN HPNDEFCAM H ON H.OID = ADNINGRESO.HPNDEFCAM
      WHERE F.GDECODIGO =  @3
      AND ADNINGRESO.ADNCENATE IN(@4, @5)
      GROUP BY F.AGRUPADOR, F.ORDEN, F.TOTALFACTURADO, F.NEVENTOS
      ORDER BY F.ORDEN DESC;`;
      parameters = [
        dto.inicioReporte,
        dto.finalReporte,
        dto.contrato1,
        dto.contrato2,
        dto.centro1,
        dto.centro2,
      ];
    } else if (dto.contrato1 === "8009") {
      query = `${common} AND G.CONTRATO = '8010'   
      WHERE 
      SLNFACTUR.SFATIPDOC = 17
      AND SLNFACTUR.SFADOCANU = N'0' 
      AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @0 AND @1
      AND GENDETCON.GDECODIGO IN(@2)
      AND SLNORDSER.SOSESTADO = 1
      GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC, SLNFACTUR.SFAVALCAR, SLNFACTUR.SFAVALREC
      ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC)
)  CONS ON CONS.AINCONSEC = ADNINGRESO.AINCONSEC 
      RIGHT JOIN GCMFICHCON F ON F.AGRUPADOR = CONS.AGRUPADOR
      LEFT JOIN HPNDEFCAM H ON H.OID = ADNINGRESO.HPNDEFCAM
      WHERE F.GDECODIGO =  '8010'
      AND ADNINGRESO.ADNCENATE IN(@3, @4)
      GROUP BY F.AGRUPADOR, F.ORDEN, F.TOTALFACTURADO, F.NEVENTOS
      ORDER BY F.ORDEN DESC;`;
      parameters = [dto.inicioReporte, dto.finalReporte, dto.contrato1, dto.centro1, dto.centro2];
    } else {
      query = `${common} AND G.CONTRATO = @2   
      WHERE 
      SLNFACTUR.SFATIPDOC = 17
      AND SLNFACTUR.SFADOCANU = N'0' 
      AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @0 AND @1
      AND GENDETCON.GDECODIGO IN(@2)
      AND SLNORDSER.SOSESTADO = 1
      GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC, SLNFACTUR.SFAVALCAR, SLNFACTUR.SFAVALREC
      ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC)
      )  CONS ON CONS.AINCONSEC = ADNINGRESO.AINCONSEC 
      RIGHT JOIN GCMFICHCON F ON F.AGRUPADOR = CONS.AGRUPADOR
      LEFT JOIN HPNDEFCAM H ON H.OID = ADNINGRESO.HPNDEFCAM
          WHERE F.GDECODIGO =  @2
          AND ADNINGRESO.ADNCENATE IN(@3, @4)
      GROUP BY F.AGRUPADOR, F.ORDEN, F.TOTALFACTURADO, F.NEVENTOS
      ORDER BY F.ORDEN DESC;`;
      parameters = [dto.inicioReporte, dto.finalReporte, dto.contrato1, dto.centro1, dto.centro2];
    }
  } else if (context === ContextsE.AGUACHICA) {
    const common = `SELECT 
    F.AGRUPADOR Agrupador,
    ISNULL(SUM(CONS.SFAVALCAR),0) TotalEjecutado,
    ISNULL(NULLIF(F.TOTALFACTURADO, 0), 0) TotalFacturado,
    COUNT(CONS.AINCONSEC) Iteraciones, 
    F.NEVENTOS Eventos,
    (F.NEVENTOS-COUNT(CONS.AINCONSEC)) EventosSobrantes,
    ISNULL((SUM(CONS.SFAVALCAR) /COUNT(CONS.AINCONSEC)),0) CmeEjecutado,
    ISNULL((F.TOTALFACTURADO / NULLIF(F.NEVENTOS, 0)), 0) CmeFacturado,
    ISNULL(F.TOTALFACTURADO -SUM(CONS.SFAVALCAR), 0) ErrorAbsoluto,
    ISNULL(ROUND(((F.TOTALFACTURADO - SUM(CONS.SFAVALCAR))/ NULLIF(F.TOTALFACTURADO, 0))*100, 2),0) ErrorRelativo,
    ISNULL(ROUND((SUM(CONS.SFAVALCAR)/ NULLIF(F.TOTALFACTURADO, 0))*100 ,2), 0) Porcentaje
     FROM ADNINGRESO RIGHT JOIN 
    (
SELECT  
    TOP 1 WITH TIES
    ISNULL(G.ORDEN, 0) ORDEN,
       ISNULL(G.AGRUPADOR, 'EVENTOS')AS AGRUPADOR,
       ADNINGRESO.AINCONSEC,
        SLNFACTUR.SFAVALCAR,
        SLNFACTUR.SFAVALREC
            FROM SLNFACTUR
             INNER JOIN ADNINGRESO ADNINGRESO ON ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
             INNER JOIN GENDETCON GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON
             INNER JOIN SLNSERPRO SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
             LEFT JOIN SLNORDSER SLNORDSER ON SLNORDSER.OID = SLNSERPRO.SLNORDSER1
             LEFT JOIN SLNSERHOJ SLNSERHOJ ON SLNSERHOJ.OID = SLNSERPRO.OID
             LEFT JOIN GENSERIPS GENSERIPS ON GENSERIPS.OID = SLNSERHOJ.GENSERIPS1
             LEFT JOIN GENARESER GENARESER ON GENARESER.OID = SLNSERPRO.GENARESER1
             LEFT JOIN GCMAGRUPGP G ON RTrim(LTrim(GENSERIPS.SIPCODIGO)) = G.COD_SERIPS`;
    if (dto.contrato1 === "8003 - 8004") {
      query = `${common} AND G.CONTRATO = '8004'  
        WHERE 
        SLNFACTUR.SFATIPDOC = 17
        AND SLNFACTUR.SFADOCANU = N'0' 
        AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @0 AND @1
        AND GENDETCON.GDECODIGO IN('8003', '8004')
        AND SLNORDSER.SOSESTADO = 1
        GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC, SLNFACTUR.SFAVALCAR, SLNFACTUR.SFAVALREC
        ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC)
)  CONS ON CONS.AINCONSEC = ADNINGRESO.AINCONSEC 
        RIGHT JOIN GCMFICHCON F ON F.AGRUPADOR = CONS.AGRUPADOR
        LEFT JOIN HPNDEFCAM H ON H.OID = ADNINGRESO.HPNDEFCAM
        WHERE F.GDECODIGO =  '8004'
        GROUP BY F.AGRUPADOR, F.ORDEN, F.TOTALFACTURADO, F.NEVENTOS
        ORDER BY F.ORDEN DESC;`;
      parameters = [dto.inicioReporte, dto.finalReporte];
    } else {
      query = `${common} AND G.CONTRATO = @2 
        WHERE 
        SLNFACTUR.SFATIPDOC = 17
        AND SLNFACTUR.SFADOCANU = N'0' 
        AND CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) BETWEEN @0 AND @1
        AND GENDETCON.GDECODIGO IN(@2)
        AND SLNORDSER.SOSESTADO = 1
        GROUP BY G.AGRUPADOR, G.ORDEN, ADNINGRESO.AINCONSEC, SLNFACTUR.SFAVALCAR, SLNFACTUR.SFAVALREC
        ORDER BY ROW_NUMBER() OVER(PARTITION BY ADNINGRESO.AINCONSEC ORDER BY G.ORDEN DESC)
)  CONS ON CONS.AINCONSEC = ADNINGRESO.AINCONSEC 
        RIGHT JOIN GCMFICHCON F ON F.AGRUPADOR = CONS.AGRUPADOR
        LEFT JOIN HPNDEFCAM H ON H.OID = ADNINGRESO.HPNDEFCAM
        WHERE F.GDECODIGO = @2 
        GROUP BY F.AGRUPADOR, F.ORDEN, F.TOTALFACTURADO, F.NEVENTOS
        ORDER BY F.ORDEN DESC`;
      parameters = [dto.inicioReporte, dto.finalReporte, dto.contrato1];
    }
  } else {
    cn.ThrBadReqExc("El context no es valido");
  }
  try {
    const result = await cn.getDataSource(context).query(query, parameters);
    return result;
  } catch (error) {
    cn.ThrBadReqExc();
  }
};
