import * as cn from "src/application/services/connection.service";
import { ContextsE } from "src/application/enums/contexts.enum";
import { GetConsumidoFacturadoDto } from "../dtos/get-consumido-facturado.dto";
import { DiferenciaConsolidadoI } from "../interfaces/diferencia-consolidado.interface";

export const getDiferenciaConsolidado = async (
  dto: GetConsumidoFacturadoDto,
  context: string
): Promise<DiferenciaConsolidadoI[]> => {
  let query: string;
  let parameters: any[] = [];
  if (context === ContextsE.VALLEDUPAR) {
    query = `SELECT   
    CONS.NContrato,
      CONS.ErrorAbsoluto Diferencia
      FROM 
      GENDETCON RIGHT JOIN(
      SELECT 
      CONS.NContrato,
      CONS.Contrato,
      SUM(CONS.TotalEjecutado) TotalEjecutado,
      MAX(CONS.TotalFacturado) TotalFacturado,
      SUM(CONS.Iteraciones) Iteraciones,
      ISNULL(ROUND ( MAX(CONS.TotalFacturado)-SUM(CONS.TotalEjecutado), 2 ),0) ErrorAbsoluto,
      ROUND( ((MAX(CONS.TotalFacturado)-SUM(CONS.TotalEjecutado))/NULLIF(MAX(CONS.TotalFacturado), 0))*100,2) ErrorRelativo,
      ROUND(((SUM(CONS.TotalEjecutado) / NULLIF(MAX(CONS.TotalFacturado),0))*100), 2) Porcentaje
      FROM GENDETCON
      RIGHT JOIN(
      SELECT   
        'ACOST' ESTADO,
        GENDETCON.GDECODIGO As NContrato,
        GENDETCON.GDENOMBRE As Contrato,
        COUNT(DISTINCT(ADNINGRESO.AINCONSEC)) Iteraciones,
        SUM(SLNSERPRO.SERCANTID * SLNSERPRO.SERVALPRO) TotalEjecutado,
        ISNULL(G.LIMITE, 0) TotalFacturado
      FROM HPNESTANC
        INNER JOIN HPNDEFCAM ON HPNESTANC.HPNDEFCAM = HPNDEFCAM.OID
          INNER JOIN ADNINGRESO ON HPNESTANC.ADNINGRES = ADNINGRESO.OID
          INNER JOIN GENPACIEN ON ADNINGRESO.GENPACIEN = GENPACIEN.OID
          INNER JOIN GENDETCON ON ADNINGRESO.GENDETCON = GENDETCON.OID
          LEFT JOIN SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
          LEFT Join SLNORDSER On SLNORDSER.OID = SLNSERPRO.SLNORDSER1
          LEFT JOIN GCMLIMPGP G ON GENDETCON.GDECODIGO = G.GDECODIGO
        WHERE GENDETCON.GDECODIGO = 'I202'
          AND ADNINGRESO.AINESTADO = 0 
          AND SLNORDSER.SOSESTADO <> 2
          AND HPNDEFCAM.HCAESTADO = 2
          AND HPNESTANC.HESFECSAL IS NULL
        GROUP BY GENDETCON.GDECODIGO, GENDETCON.GDENOMBRE, G.LIMITE
        UNION
      Select
        'FACT' ESTADO,
        GENDETCON.GDECODIGO As NContrato,
        GENDETCON.GDENOMBRE As Contrato,
        COUNT(SLNFACTUR.SFATOTFAC) Iteraciones,
        SUM(SLNFACTUR.SFAVALCAR) TotalEjecutado,
        ISNULL(G.LIMITE, 0) TotalFacturado
      From SLNFACTUR SLNFACTUR
        Inner Join ADNINGRESO ADNINGRESO On ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
        Inner Join GENDETCON GENDETCON On GENDETCON.OID = SLNFACTUR.GENDETCON
        LEFT JOIN HPNDEFCAM E ON ADNINGRESO.HPNDEFCAM = E.OID
        LEFT JOIN HPNSUBGRU F ON F.OID = E.HPNSUBGRU
        LEFT JOIN GCMLIMPGP G ON G.GDECODIGO = GENDETCON.GDECODIGO
      Where SLNFACTUR.SFAFECFAC Between @0 AND @1
        AND  SLNFACTUR.SFADOCANU = N'0'
        and SLNFACTUR.SFATIPDOC = 17
        AND GENDETCON.GDECODIGO = 'I202'
      GROUP BY GENDETCON.GDECODIGO, GENDETCON.GDENOMBRE, G.LIMITE)AS CONS ON CONS.NContrato = GENDETCON.GDECODIGO
      GROUP BY CONS.NContrato, CONS.Contrato)CONS ON CONS.NContrato = GENDETCON.GDECODIGO 
      WHERE GENDETCON.GDECODIGO IN('I202')
      ORDER BY CONS.nContrato;`;
    parameters = [dto.inicioReporte, dto.finalReporte];
  } else if (context === ContextsE.ALTACENTRO) {
    query = `SELECT 
    CASE WHEN CONS.NContrato = '8006' THEN '8005 - 8006' ELSE CONS.NContrato
    END NContrato,
  CONS.ErrorAbsoluto Diferencia
  FROM 
  GENDETCON RIGHT JOIN(
  SELECT 
  CONS.NContrato,
  CONS.Contrato,
  SUM(CONS.TotalEjecutado) TotalEjecutado,
  MAX(CONS.TotalFacturado) TotalFacturado,
  SUM(CONS.Iteraciones) Iteraciones,
  ISNULL(ROUND ( MAX(CONS.TotalFacturado)-SUM(CONS.TotalEjecutado), 2 ),0) ErrorAbsoluto,
  ROUND( ((MAX(CONS.TotalFacturado)-SUM(CONS.TotalEjecutado))/NULLIF(MAX(CONS.TotalFacturado), 0))*100,2) ErrorRelativo,
  ROUND(((SUM(CONS.TotalEjecutado) / NULLIF(MAX(CONS.TotalFacturado),0))*100), 2) Porcentaje
  FROM GENDETCON
  RIGHT JOIN(
  SELECT   
    'ACOST' ESTADO,
    GENDETCON.GDECODIGO As NContrato,
    GENDETCON.GDENOMBRE As Contrato,
    COUNT(DISTINCT(ADNINGRESO.AINCONSEC)) Iteraciones,
    SUM(SLNSERPRO.SERCANTID * SLNSERPRO.SERVALPRO) TotalEjecutado,
    ISNULL(G.LIMITE, 0) TotalFacturado
  FROM HPNESTANC
    INNER JOIN HPNDEFCAM ON HPNESTANC.HPNDEFCAM = HPNDEFCAM.OID
      INNER JOIN ADNINGRESO ON HPNESTANC.ADNINGRES = ADNINGRESO.OID
      INNER JOIN GENPACIEN ON ADNINGRESO.GENPACIEN = GENPACIEN.OID
      INNER JOIN GENDETCON ON ADNINGRESO.GENDETCON = GENDETCON.OID
      LEFT JOIN SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
      LEFT Join SLNORDSER On SLNORDSER.OID = SLNSERPRO.SLNORDSER1
      LEFT JOIN GCMLIMPGP G ON GENDETCON.GDECODIGO = G.GDECODIGO
    WHERE GENDETCON.GDECODIGO BETWEEN '8001' AND '8010'
      AND ADNINGRESO.AINESTADO = 0 
      AND SLNORDSER.SOSESTADO <> 2
      AND HPNDEFCAM.HCAESTADO = 2
      AND HPNESTANC.HESFECSAL IS NULL
      AND HPNDEFCAM.ADNCENATE IN(@2, @3)
    GROUP BY GENDETCON.GDECODIGO, GENDETCON.GDENOMBRE, G.LIMITE
    UNION
  Select
    'FACT' ESTADO,
    GENDETCON.GDECODIGO As NContrato,
    GENDETCON.GDENOMBRE As Contrato,
    COUNT(SLNFACTUR.SFATOTFAC) Iteraciones,
    SUM(SLNFACTUR.SFAVALCAR) TotalEjecutado,
    ISNULL(G.LIMITE, 0) TotalFacturado
  From SLNFACTUR SLNFACTUR
    Inner Join ADNINGRESO ADNINGRESO On ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
    Inner Join GENDETCON GENDETCON On GENDETCON.OID = SLNFACTUR.GENDETCON
    LEFT JOIN HPNDEFCAM E ON ADNINGRESO.HPNDEFCAM = E.OID
    LEFT JOIN HPNSUBGRU F ON F.OID = E.HPNSUBGRU
    LEFT JOIN GCMLIMPGP G ON G.GDECODIGO = GENDETCON.GDECODIGO
  Where SLNFACTUR.SFAFECFAC Between @0 And @1
    AND  SLNFACTUR.SFADOCANU = N'0'
    and SLNFACTUR.SFATIPDOC = 17
    AND GENDETCON.GDECODIGO BETWEEN '8001' AND '8010'
    AND ADNINGRESO.ADNCENATE IN(@2 ,@3)
  GROUP BY GENDETCON.GDECODIGO, GENDETCON.GDENOMBRE, G.LIMITE)AS CONS ON CONS.NContrato = GENDETCON.GDECODIGO
  GROUP BY CONS.NContrato, CONS.Contrato)CONS ON CONS.NContrato = GENDETCON.GDECODIGO 
  WHERE GENDETCON.GDECODIGO IN('8001', '8006', '8009', '8010')
  ORDER BY CONS.nContrato`;
    parameters = [dto.inicioReporte, dto.finalReporte, dto.centro1, dto.centro2];
  } else if (context === ContextsE.AGUACHICA) {
    query = `SELECT 
    CONS.NContrato,
    ISNULL(ROUND ( MAX(CONS.TotalFacturado)-SUM(CONS.TotalEjecutado), 2 ),0) Diferencia
    FROM GENDETCON
    RIGHT JOIN(
    (SELECT   
      GENDETCON.GDECODIGO As NContrato,
      SUM(SLNSERPRO.SERCANTID * SLNSERPRO.SERVALPRO) TotalEjecutado,
      ISNULL(G.LIMITE, 0) TotalFacturado
    FROM HPNESTANC
      INNER JOIN HPNDEFCAM ON HPNESTANC.HPNDEFCAM = HPNDEFCAM.OID
        INNER JOIN ADNINGRESO ON HPNESTANC.ADNINGRES = ADNINGRESO.OID
        INNER JOIN GENPACIEN ON ADNINGRESO.GENPACIEN = GENPACIEN.OID
        INNER JOIN GENDETCON ON ADNINGRESO.GENDETCON = GENDETCON.OID
        LEFT JOIN SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
        LEFT Join SLNORDSER On SLNORDSER.OID = SLNSERPRO.SLNORDSER1
        LEFT JOIN GCMLIMPGP G ON GENDETCON.GDECODIGO = G.GDECODIGO
      WHERE GENDETCON.GDECODIGO IN('8000', '8001', '8002', '8005')
        AND ADNINGRESO.AINESTADO = 0 
        AND SLNORDSER.SOSESTADO <> 2
        AND HPNDEFCAM.HCAESTADO = 2
        AND HPNESTANC.HESFECSAL IS NULL
      GROUP BY GENDETCON.GDECODIGO, GENDETCON.GDENOMBRE, G.LIMITE
  UNION
  SELECT   
      '8003 - 8004' As NContrato,
      SUM(SLNSERPRO.SERCANTID * SLNSERPRO.SERVALPRO) TotalEjecutado,
      ISNULL(G.LIMITE, 0) TotalFacturado
    FROM HPNESTANC
      INNER JOIN HPNDEFCAM ON HPNESTANC.HPNDEFCAM = HPNDEFCAM.OID
        INNER JOIN ADNINGRESO ON HPNESTANC.ADNINGRES = ADNINGRESO.OID
        INNER JOIN GENPACIEN ON ADNINGRESO.GENPACIEN = GENPACIEN.OID
        INNER JOIN GENDETCON ON ADNINGRESO.GENDETCON = GENDETCON.OID
        LEFT JOIN SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
        LEFT Join SLNORDSER On SLNORDSER.OID = SLNSERPRO.SLNORDSER1
        LEFT JOIN GCMLIMPGP G ON  G.GDECODIGO = '8004'
      WHERE GENDETCON.GDECODIGO IN ('8003', '8004')
        AND ADNINGRESO.AINESTADO = 0 
        AND SLNORDSER.SOSESTADO <> 2
        AND HPNDEFCAM.HCAESTADO = 2
        AND HPNESTANC.HESFECSAL IS NULL
      GROUP BY GENDETCON.GDECODIGO, GENDETCON.GDENOMBRE, G.LIMITE
  )
      UNION
    (Select
      GENDETCON.GDECODIGO As NContrato,
      SUM(SLNFACTUR.SFAVALCAR) TotalEjecutado,
      ISNULL(G.LIMITE, 0) TotalFacturado
    From SLNFACTUR SLNFACTUR
      Inner Join ADNINGRESO ADNINGRESO On ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
      Inner Join GENDETCON GENDETCON On GENDETCON.OID = SLNFACTUR.GENDETCON
      LEFT JOIN HPNDEFCAM E ON ADNINGRESO.HPNDEFCAM = E.OID
      LEFT JOIN HPNSUBGRU F ON F.OID = E.HPNSUBGRU
      LEFT JOIN GCMLIMPGP G ON G.GDECODIGO = GENDETCON.GDECODIGO
    Where CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) Between @0 And @1
      AND  SLNFACTUR.SFADOCANU = N'0'
      and SLNFACTUR.SFATIPDOC = 17
      AND GENDETCON.GDECODIGO IN ('8000', '8001', '8002', '8005')
    GROUP BY GENDETCON.GDECODIGO, GENDETCON.GDENOMBRE, G.LIMITE
  UNION
  Select
      '8003 - 8004' As NContrato,
      SUM(SLNFACTUR.SFAVALCAR) TotalEjecutado,
      ISNULL(G.LIMITE, 0) TotalFacturado
    From SLNFACTUR SLNFACTUR
      Inner Join ADNINGRESO ADNINGRESO On ADNINGRESO.OID = SLNFACTUR.ADNINGRESO
      Inner Join GENDETCON GENDETCON On GENDETCON.OID = SLNFACTUR.GENDETCON
      LEFT JOIN HPNDEFCAM E ON ADNINGRESO.HPNDEFCAM = E.OID
      LEFT JOIN HPNSUBGRU F ON F.OID = E.HPNSUBGRU
      LEFT JOIN GCMLIMPGP G ON G.GDECODIGO = '8004'
    Where CONVERT(DATE, SLNFACTUR.SFAFECFAC, 103) Between @0 And @1
      AND  SLNFACTUR.SFADOCANU = N'0'
      and SLNFACTUR.SFATIPDOC = 17
      AND GENDETCON.GDECODIGO IN('8003', '8004')
    GROUP BY GENDETCON.GDECODIGO, GENDETCON.GDENOMBRE, G.LIMITE
  )
  )AS CONS ON CONS.NContrato = GENDETCON.GDECODIGO
    GROUP BY CONS.NContrato
    ORDER BY CONS.NContrato;`;
    parameters = [dto.inicioReporte, dto.finalReporte];
  } else {
    cn.ThrBadReqExc("El context no es valido");
  }
  try {
    const result = await cn.getDataSource(context).query(query, parameters);
    return result;
  } catch (error) {
    cn.ThrBadReqExc();
  }
};
