import * as cn from "src/application/services/connection.service";
import { ContextsE } from "src/application/enums/contexts.enum";
import { GetConsumidoAcostadoDto } from "../dtos/get-consumido-acostado.dto";
import { ConsumidoI } from "../interfaces/consumido.interface";

export const getConsumidoAcostadoActual = async (
  dto: GetConsumidoAcostadoDto,
  context: string
): Promise<ConsumidoI[]> => {
  let query: string;
  let parameters: any[] = [];
  const common = `SELECT   
  GENDETCON.GDECODIGO As NContrato,
  GENDETCON.GDENOMBRE As Contrato,
  COUNT(DISTINCT(ADNINGRESO.AINCONSEC)) Iteraciones,
  SUM(SLNSERPRO.SERCANTID * SLNSERPRO.SERVALPRO) TotalEjecutado,
  ISNULL(G.LIMITE, 0) TotalFacturado,
  ISNULL((G.LIMITE -SUM(SLNSERPRO.SERCANTID * SLNSERPRO.SERVALPRO)), 0) ErrorAbsoluto,
  ISNULL(((G.LIMITE - SUM(SLNSERPRO.SERCANTID * SLNSERPRO.SERVALPRO)) / G.LIMITE)*100, 0) ErrorRelativo,
  ISNULL(ROUND(((SUM(SLNSERPRO.SERCANTID * SLNSERPRO.SERVALPRO) / G.LIMITE)*100), 2),0) Porcentaje
FROM HPNESTANC
  INNER JOIN HPNDEFCAM ON HPNESTANC.HPNDEFCAM = HPNDEFCAM.OID
    --INNER JOIN HPNSUBGRU ON HPNSUBGRU.OID = HPNDEFCAM.HPNSUBGRU
    INNER JOIN ADNINGRESO ON HPNESTANC.ADNINGRES = ADNINGRESO.OID
    INNER JOIN GENPACIEN ON ADNINGRESO.GENPACIEN = GENPACIEN.OID
    INNER JOIN GENDETCON ON ADNINGRESO.GENDETCON = GENDETCON.OID
    LEFT JOIN SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
    LEFT Join SLNORDSER On SLNORDSER.OID = SLNSERPRO.SLNORDSER1
    LEFT JOIN GCMLIMPGP G ON GENDETCON.GDECODIGO = G.GDECODIGO`;
  if (context === ContextsE.VALLEDUPAR) {
    query = `${common} WHERE GENDETCON.GDECODIGO = 'I202'
    AND ADNINGRESO.AINESTADO = 0 
    AND SLNORDSER.SOSESTADO <> 2
    AND HPNDEFCAM.HCAESTADO = 2
    AND HPNESTANC.HESFECSAL IS NULL
  GROUP BY GENDETCON.GDECODIGO, GENDETCON.GDENOMBRE, G.LIMITE
  ORDER BY GENDETCON.GDECODIGO;`;
  } else if (context === ContextsE.ALTACENTRO) {
    query = `${common} WHERE GENDETCON.GDECODIGO BETWEEN '8001' AND '8010'
    AND ADNINGRESO.AINESTADO = 0 
    AND SLNORDSER.SOSESTADO <> 2
    AND HPNDEFCAM.HCAESTADO = 2
    AND HPNESTANC.HESFECSAL IS NULL
    AND ADNINGRESO.ADNCENATE IN (@0, @1)
  GROUP BY GENDETCON.GDECODIGO, GENDETCON.GDENOMBRE, G.LIMITE
  ORDER BY GENDETCON.GDECODIGO;`;
    parameters = [dto.centro1, dto.centro2];
  } else if (context === ContextsE.AGUACHICA) {
    query = `${common} WHERE GENDETCON.GDECODIGO IN ('8000', '8001', '8002', '8005')
    AND ADNINGRESO.AINESTADO = 0 
    AND SLNORDSER.SOSESTADO <> 2
    AND HPNDEFCAM.HCAESTADO = 2
    AND HPNESTANC.HESFECSAL IS NULL
  GROUP BY GENDETCON.GDECODIGO, GENDETCON.GDENOMBRE, G.LIMITE
  UNION
  SELECT   
  '8003 - 8004' As NContrato,
  'PGP ASMET SALUD SUBS - CONTR' As Contrato,
  COUNT(DISTINCT(ADNINGRESO.AINCONSEC)) Iteraciones,
  SUM(SLNSERPRO.SERCANTID * SLNSERPRO.SERVALPRO) TotalEjecutado,
  ISNULL(G.LIMITE, 0) TotalFacturado,
  ISNULL((G.LIMITE -SUM(SLNSERPRO.SERCANTID * SLNSERPRO.SERVALPRO)), 0) ErrorAbsoluto,
  ISNULL(((G.LIMITE - SUM(SLNSERPRO.SERCANTID * SLNSERPRO.SERVALPRO)) / G.LIMITE)*100, 0) ErrorRelativo,
  ISNULL(ROUND(((SUM(SLNSERPRO.SERCANTID * SLNSERPRO.SERVALPRO) / G.LIMITE)*100), 2),0) Porcentaje
FROM HPNESTANC
  INNER JOIN HPNDEFCAM ON HPNESTANC.HPNDEFCAM = HPNDEFCAM.OID
    INNER JOIN ADNINGRESO ON HPNESTANC.ADNINGRES = ADNINGRESO.OID
    INNER JOIN GENPACIEN ON ADNINGRESO.GENPACIEN = GENPACIEN.OID
    INNER JOIN GENDETCON ON ADNINGRESO.GENDETCON = GENDETCON.OID
    LEFT JOIN SLNSERPRO ON SLNSERPRO.ADNINGRES1 = ADNINGRESO.OID
    LEFT Join SLNORDSER On SLNORDSER.OID = SLNSERPRO.SLNORDSER1
    LEFT JOIN GCMLIMPGP G ON G.GDECODIGO = '8004'
  WHERE GENDETCON.GDECODIGO IN ('8003', '8004')
    AND ADNINGRESO.AINESTADO = 0 
    AND SLNORDSER.SOSESTADO <> 2
    AND HPNDEFCAM.HCAESTADO = 2
    AND HPNESTANC.HESFECSAL IS NULL
    GROUP BY G.LIMITE
  ORDER BY GENDETCON.GDECODIGO;`;
  } else {
    cn.ThrBadReqExc("El context no es valido");
  }
  try {
    const result = await cn.getDataSource(context).query(query, parameters);
    return result;
  } catch (error) {
    cn.ThrBadReqExc();
  }
};
